version: "3.6"
services:

  caddy:
    build:
      context: .
      dockerfile: caddy/Dockerfile
    image: openindoor-caddy
    restart: unless-stopped
    ports:
      - "9092:80"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - ./data:/srv/data
      - caddy_data:/data
      - caddy_config:/config
    command: caddy run --config /etc/caddy/Caddyfile --adapter caddyfile --watch

  cad2gis:
    build:
      context: .
      dockerfile: Dockerfile
    image: openindoor/cad2gis
    cpus: 1
    restart: unless-stopped
    working_dir: /openindoor
    volumes:
    - ./data:/data
    - ./log:/openindoor/log
    - ./cad2gis.py:/openindoor/cad2gis.py
    - ./autocad-to-ascii_dxf.sh:/openindoor/autocad-to-ascii_dxf.sh
    command: /openindoor/cad2gis.py

volumes:
  caddy_data:
  caddy_config: